apiVersion: v1
kind: Namespace
metadata:
  name: web-apps
---
apiVersion: v1
kind: CongifMap
metadata:
  name: webapp1-content
  namespace: web-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    	<meta charset="UTF-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title>Webapp1</title>
    </head>
    <body>
    	<h1>Welcome in the web app 1 !</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  repicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-content
        configMap:
          name: webapp1-content

---

apiVersion: v1
kind: Service
metadata:
  name: webapp1
spec:
  type: NodePort
  selector:
    app: webapp1
  ports:
  - port: 80
    nodePort: 30001

---

apiVersion: v1
kind: CongifMap
metadata:
  name: webapp2-content
  namespace: web-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    	<meta charset="UTF-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title>Webapp2</title>
    </head>
    <body>
    	<h1>Welcome in the web app 2 !</h1>
    </body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  repicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-content
        configMap:
          name: webapp2-content

---

apiVersion: v1
kind: Service
metadata:
  name: webapp2
spec:
  type: NodePort
  selector:
    app: webapp2
  ports:
  - port: 80
    nodePort: 30002

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: app1.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
        service:
          name: webapp1
          port:
            number: 80
  - host: app2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
        service:
          name: webapp2
          port:
            number: 80

