Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20240905.1"
  config.vm.synced_folder "./src", "/home/"
  config.vm.define "gfranqueS" do |control|
    control.vm.hostname = "gfranqueS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "gfranqueS"
    end
    control.vm.provision "shell", path: "server.sh"
  end
end
