services:
  gitlab:
    container_name: gitlab
    build:
      context: ./gitlab
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2222:22"
    hostname: localhost
    shm_size: '1024m'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

    
