Vagrant.configure(2) do |config|
	config.vm.box = "debian/bullseye64"
	config.vm.box_version = "11.20240905.1"
	config.vm.define "gfranqueS" do |control|
	  control.vm.hostname = "gfranqueS"
	  control.vm.network "private_network", ip: "192.168.56.110"
	  config.vm.network "forwarded_port", guest: 8080, host: 8080
	  config.vm.network "forwarded_port", guest: 8443, host: 8443  
	  config.vm.network "forwarded_port", guest: 6443, host: 6443
	  control.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 4
		v.name = "gfranqueS"
	  end 
	  control.vm.provision "file", source: "./ingress.yaml", destination: "~/ingress.yaml"
  
	  control.vm.provision "shell", path: "server.sh"
	end 
  end